import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Sections/Header";
import Footer from "@/components/Sections/Footer";
import StoreProvider from "@/Provider/StoreProvider";
import AuthProvider from "@/Provider/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
// import { ToastContainer, toast } from 'react-toastify';
// import 'react-toastify/dist/ReactToastify.css';
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
       <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <Header/>
          {children}
          <Footer/>
          {/* <ToastContainer/> */}
          <Toaster />
        </AuthProvider>
      </body>
    </html> 
    </StoreProvider>
   
  );
}
